from pydantic import BaseModel, Field, field_validator
from typing import Optional
from datetime import date, datetime
from decimal import Decimal
from uuid import UUID

class ExpenseBase(BaseModel):
    amount: Decimal = Field(..., gt=0, decimal_places=2)
    category: str = Field(..., min_length=1)
    description: Optional[str] = None
    expense_date: date
    request_id: str = Field(..., description="Unique ID generated by frontend to prevent duplicates")

    @field_validator('amount')
    @classmethod
    def amount_must_be_positive(cls, v):
        if v <= 0:
            raise ValueError('Amount must be greater than zero')
        return v

class ExpenseCreate(ExpenseBase):
    pass

class ExpenseResponse(ExpenseBase):
    id: UUID
    created_at: datetime

    class Config:
        from_attributes = True